name: Generate and Upload Zip Artifact

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run the Java program
        run: java -jar target/*-jar-with-dependencies.jar

      - name: Rename ZIP with version
        run: mv output.zip output-${{ steps.extract_version.outputs.version }}.zip

      - name: Upload versioned ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-zip-${{ steps.extract_version.outputs.version }}
          path: output-${{ steps.extract_version.outputs.version }}.zip
